# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      TEST_DATABASE_URL: ${{secrets.TEST_DATABASE_URL}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      NODE_ENV: ${{secrets.NODE_ENV}}
      PRODUCTION_DATABASE_URL: ${{secrets.PRODUCTION_DATABASE_URL}}


    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn build
    - run: yarn test
